name: Crux Build Beta
on: 
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    build:

        runs-on: ubuntu-latest
      
        steps:
          - uses: actions/checkout@v3
          - uses: pnpm/action-setup@v2
            with:
                version: 6.0.2
          - name: Install dependencies
            run: pnpm install
          - name: Build Dist
            run: pnpm run build
          - name: Install zip
            uses: montudor/action-zip@v1
          - name: Zip Files
            run: zip -qq -r crux-beta.zip templates annotation-setting.yaml settings.yaml theme.yaml
          - name: Create a Release
            uses: elgohr/Github-Release-Action@v4
            env:
                GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
            with:
                prerelease: true
                tag: ${{ vars.GITHUB_RUN_ID }}
                title: Crux Beta | ${{vars.GITHUB_RUN_ATTEMPT}} | ${{ vars.GITHUB_RUN_ID }}
                artifact: crux-beta.zip
                body: Auto Build | ${{ vars.GITHUB_RUN_ID }}</br>Commit ${{ github.sha }}</br>Branch ${{ github.ref }}


